networks:
  dev-langflow:

services:
  langflow-dev:
    build:
      context: .
      dockerfile: docker/dev.Dockerfile
    image: langflow-dev
    container_name: langflow-dev
    restart: always
    ports:
      - "7860:7860"
      - "3000:3000"
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - LANGFLOW_DATABASE_URL=postgresql://langflow:langflow@langflow-pg:5432/langflow
      - LANGFLOW_SUPERUSER=langflow
      - LANGFLOW_SUPERUSER_PASSWORD=langflow
      - LANGFLOW_CONFIG_DIR=/var/lib/langflow
    env_file:
      - ./.env
    volumes:
      - ./:/app
    depends_on:
      - langflow-pg # Dependência no seu banco de dados existente


  langflow-pg:
    container_name: langflow-pg
    # image: pgvector/pgvector:pg16
    image: postgres:16
    environment:
      POSTGRES_USER: langflow
      POSTGRES_PASSWORD: langflow
      POSTGRES_DB: langflow
    ports:
      - "5432:5432"
    volumes:
      - ./langflow-pg/data:/var/lib/postgresql/data

